# Generated by Django 5.0.14 on 2026-03-31 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donor_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='donation',
            name='donor_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
