# Generated by Django 5.0.14 on 2026-04-01 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_alter_campaign_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='bank_account_number',
            field=models.CharField(blank=True, help_text="Seeker's Bank Account Number", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='bank_name',
            field=models.CharField(blank=True, help_text="Name of the Seeker's bank", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='ifsc_code',
            field=models.CharField(blank=True, help_text='IFSC Code for the bank branch', max_length=20, null=True),
        ),
    ]
